# Generated by Django 3.2.18 on 2023-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software Developer'), (2, 'QA Engineer'), (3, 'Marketing Specialist')], default=1),
            preserve_default=False,
        ),
    ]
