# Generated by Django 3.2.18 on 2023-03-30 12:50

import django.core.validators
from django.db import migrations, models
import my_plant_app.main.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.main.custom_validators.validate_first_letter_should_be_capital])),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_app.main.custom_validators.validate_first_letter_should_be_capital])),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
