# Generated by Django 3.2.18 on 2023-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
