     # Generated by Django 3.2.18 on 2023-03-29 12:01

import django.core.validators
from django.db import migrations, models
import expenses_tracker.main.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker.main.custom_validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker.main.custom_validators.validate_only_letters])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[expenses_tracker.main.custom_validators.MaxFileSizeInMbValidator(5)])),
            ],
        ),
    ]
